version: '3.1'

services:
  db:
    image: mysql
    restart: always
    ports:
    - 3306:3306
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./:/src
      - ./conf.cnf:/etc/mysql/my.cnf
      - ./sql:/docker-entrypoint-initdb.d
    working_dir: /src
